###服务启动端口号
server:
  port: 8300
###服务名称(服务注册到eureka名称)
spring:
  application:
    name: app-mayikt-member
###服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka

####swagger相关配置
swagger:
  base-package: com.ly.member.service  #扫包范围
  title: SpringCloud2.x构建微服务电商项目-会员服务接口 #文档标题
  ####文档描述
  description: 该项目“基于SpringCloud2.x构建微服务电商项目”由每特教育|蚂蚁课堂版权所有，未经过允许的情况下，私自分享视频和源码属于违法行为。
  version: 1.1  ###版本号
  terms-of-service-url: www.mayikt.com #联系网址
  contact:
    name: ly
    email: 418383041@qq.com
